baseURL: https://navendu.me/
languageCode: en-us
title: "Navendu Pottekkat"
theme: ["PaperMod", "plausible-hugo"]
paginate: 200000

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableGitInfo: true

# googleAnalytics: G-VC68GQDE93

# disqusShortname: navendu

minify:
    disableXML: true
    minifyOutput: true

taxonomies:
  category: categories
  series: series
  tag: tags

related:
  includeNewer: true
  indices:
  - name: categories
    weight: 40
  - name: tags
    weight: 60
  threshold: 90
  toLower: false

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Navendu Pottekkat"
    description: "\"May the Source Be with You\" is Navendu Pottekkat's personal blog, where he writes about his work and life as an open source contributor/maintainer."
    keywords: [Navendu, Pottekkkat, Blog, Portfolio, Resume]
    author: "Navendu Pottekkat"
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light, auto
    disableThemeToggle: true

    mainSections: ['posts']
    dailySections: ['daily']
    newsletterSections: ['newsletter']
    mermaid:
      theme: "dark"
      align: "center"

    plausible:
      enable: true
      domain: "navendu.me"
      proxy_netlify: true
      outbound_link: true
      gitstar: false

    ShowReadingTime: true
    ShowLastMod: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowWordCount: false
    ShowRssButtonInSectionTermList: true
    UseHugoToc: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    images: ["images/preview.png","Navendu Pottekkat", "https://navendu.me/"]

    # home-info mode
    homeInfoParams:
        Title: "May the Source Be with You"
        Content:
          Intro: I'm Navendu, and welcome to my brain dump.
          About: I write about my work and life as an open source contributor/maintainer and an amateur [policy analyst](/categories/public-policy/) ([what am I doing now?](/now/)).
          Action: If you're here for the first time, try my [featured posts](/categories/featured/) or learn more [about me](/about). Make sure to subscribe via [email](/subscribe) or [RSS](/index.xml) to get regular updates.

    subscribeInfo:
      Text: If you liked this post, check out my [featured posts](/categories/featured) or learn more [about me](/about).

    socialIcons:
        - name: email
          url: "mailto:navendu@apache.org"
        # - name: telegram
        #   url: "https://t.me/MayTheSourceBeWithYou"
        - name: github
          url: "https://github.com/pottekkat"
        - name: linkedin
          url: "https://www.linkedin.com/in/realPottekkat/"
        # - name: medium
        #   url: "https://medium.com/@pottekkat"
        # - name: stackoverflow
        #   url: "https://stackoverflow.com/users/12424846/navendu-pottekkat"
        - name: twitter
          url: "https://twitter.com/realPottekkat"
        # - name: mastodon
        #   url: "https://fosstodon.org/@sudo_navendu"
        # - name: facebook
        #   url: "https://www.facebook.com/realPottekkat/"
        # - name: instagram
        #   url: "https://www.instagram.com/realPottekkat/"
        - name: youtube
          url: "https://youtube.com/@realPottekkat"
        # - name: goodreads
        #   url: "https://www.goodreads.com/user/show/83926433-navendu-pottekkat"
        - name: rss
          url: /index.xml
    
    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/pottekkat/personal-website/blob/hugo/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.1
        minMatchCharLength: 0
        limit: 5
        keys: ["title", "permalink", "summary", "content", "categories"]
menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 20
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 30
        - identifier: daily
          name: Daily Logs
          url: /dailies/
          weight: 40
        - identifier: about
          name: About
          url: /about/
          weight: 50
        - identifier: subscribe
          name: Subscribe
          url: /subscribe/
          weight: 60

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
